### ISSUE TITLE
more help please

### ISSUE THREAD

**Issue by smartekIT** [bergdahl/RemoteService#1]
Hi,
where should we install this, in the target machine where we want to restart service on? or on our machine which we use to control the target machine? or this tool has to be installed on both, target and server?

Thanks

**Comment by bergdahl** [comment]
You install it on the machine you use to control the target machine.

**Comment by smartekIT** [comment]
getting the following: (note I tried with the machine name and machine IP but all failed)
<pre>
Admin$ logon result: 5 (5)
InvalidOperationException
Cannot open Service Control Manager on computer '10.1.1.106'. This operation might require other privileges.
System.InvalidOperationException: Cannot open Service Control Manager on computer '10.1.1.106'. This operation might require other privileges. ---> System.ComponentModel.Win32Exception: Access is denied
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.GetDataBaseHandleWithAccess(String machineName, Int32 serviceControlManaqerAccess)
   at System.ServiceProcess.ServiceController.GetDataBaseHandleWithConnectAccess()
   at System.ServiceProcess.ServiceController.GenerateNames()
   at System.ServiceProcess.ServiceController.get_ServiceName()
   at System.ServiceProcess.ServiceController.GenerateStatus()
   at System.ServiceProcess.ServiceController.get_Status()
   at RemoteService.ServiceHelper.StopService() in C:\c\RemoteService\src\ServiceHelper.cs:line 131
   at RemoteService.ServiceHelper.ControlService(String action) in C:\c\RemoteService\src\ServiceHelper.cs:line 43
System.ComponentModel.Win32Exception (0x80004005): Access is denied
Exiting with code UnknownFailure (8)
</pre>

**Comment by bergdahl** [comment]
The first error (Admin$ logon result: 5) basically tells thyat you are not using an administrator account. You need to enter a username/password that have admin level access on the remote machine.

**Comment by smartekIT** [comment]
I do use admin account, the remote pc is setting next to me and only has one user account. the account didn't have a password, so I added password to it so to try.
It's a local offline account not microsoft online account.

**Comment by bergdahl** [comment]
If it is a local account you might need to enter the account name in the form of COMPUTERNAME\USERNAME. 

To test, just open Explorer and enter \\COMPUTERNAME\$Admin in the search field. It will tell you if you got the username right.

**Comment by smartekIT** [comment]
The test explorer command doesn't work.
adjusting the username format in your script doesn't work.
access the pc from network is working when providing the credentials.
remote pc has:'
network set to private
Windows firewall turned off
Network discovery is turned on and shares discoverable from network.

**Comment by smartekIT** [comment]
Hi letting you know that to get this tool works, I had to apply the following commands on the target machine (Windows 10 non domain):
<pre>
Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory Private
Enable-PSRemoting -Force
winrm quickconfig
winrm set winrm/config/service/auth '@{Basic="true"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/service/auth '@{CbtHardeningLevel="relaxed"}'
gpupdate /force
</pre>

**Comment by bergdahl** [comment]
OK, cool. I don't have any non domain joined machines to test with.
